## Numpy Exercises

In [2]:
import numpy as np

In [4]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

In [5]:
a[a>0]

array([ 4, 10, 12, 23,  3])

In [7]:
len(a[a>0])

5

In [10]:
len(a[a//2==0])

3

In [12]:
a + 3

array([ 7, 13, 15, 26,  1,  2,  3,  3,  3, -3,  6, -4])

In [19]:
len(a[a+3>0])

10

In [20]:
a ** 2

array([ 16, 100, 144, 529,   4,   1,   0,   0,   0,  36,   9,  49])

In [21]:
np.mean(a**2), np.std(a**2)

(74.0, 144.0243035046516)

In [22]:
# Q6 A common statistical operation on a dataset is centering.
# This means to adjust the data such that the mean of the data is 0.
# This is done by subtracting the mean from each data point.
# Center the data set. See this link for more on centering.

a_min_mean = a - np.mean(a)
a_min_mean

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

In [23]:
a[0]

4

In [26]:
# Q7 Calculate the z-score for each data point. Recall that the z-score is given by:
# Z = (x − μ) / σ

z_scores = []

for i in a:
    each_z = (i - np.mean(a))/np.std(a)
    z_scores.append(each_z)

z_scores

[0.12403473458920847,
 0.8682431421244593,
 1.116312611302876,
 2.4806946917841692,
 -0.6201736729460423,
 -0.49613893835683387,
 -0.3721042037676254,
 -0.3721042037676254,
 -0.3721042037676254,
 -1.116312611302876,
 0.0,
 -1.2403473458920846]