## Numpy Exercises Part 1

## Setup 1 - one-dimentional array

In [28]:
import numpy as np

In [2]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [7]:
# Use python's built in functionality/operators to determine the following:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list
sum_of_a = sum(a)
sum_of_a

55

In [11]:
a_array = np.array(a)
a_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list
min_of_a = min(a_array)
min_of_a

1

In [16]:
# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list
max_of_a = max(a_array)
max_of_a

10

In [17]:
# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list
mean_of_a = np.mean(a_array)
mean_of_a

5.5

In [18]:
# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together
product_of_a = np.product(a_array)
product_of_a

3628800

In [19]:
# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]
squares_of_a = a_array**2
squares_of_a

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [20]:
# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers
odds_in_a = a_array[a_array//2 != 1]
odds_in_a

array([ 1,  4,  5,  6,  7,  8,  9, 10])

In [21]:
# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.
evens_in_a = a_array[a_array//2 == 0]
evens_in_a

array([1])

## Setup 2 - two-dimentional array

In [60]:
b = [
    [3, 4, 5],
    [6, 7, 8]
]

In [33]:
type(b)

list

In [34]:
# Exercise 1 - refactor the following to use numpy.
# Use sum_of_b as the variable.
#**Hint, you'll first need to make sure that the "b" variable is a numpy array**

b = np.array(b)
type(b)

numpy.ndarray

In [35]:
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)

sum_of_b

33

In [36]:
b.sum()

33

In [37]:
# Exercise 2 - refactor the following to use numpy. 
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])
min_of_b

3

In [38]:
b.min()

3

In [39]:
# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])
max_of_b

8

In [40]:
b.max()

8

In [41]:
# Exercise 4 - refactor the following using numpy to find the mean of b
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))
mean_of_b

5.5

In [42]:
b.mean()

5.5

In [43]:
# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number
product_of_b

20160

In [44]:
b.prod()

20160

In [45]:
# Exercise 6 - refactor the following to use numpy to find the list of squares 
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)
squares_of_b

[9, 16, 25, 36, 49, 64]

In [46]:
b**2

array([[ 9, 16, 25],
       [36, 49, 64]])

In [47]:
# Exercise 7 - refactor using numpy to determine the odds_in_b
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)
odds_in_b

[3, 5, 7]

In [48]:
b[b%2 != 0]

array([3, 5, 7])

In [49]:
# Exercise 8 - refactor the following to use numpy to filter only the even numbers
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)
evens_in_b            

[4, 6, 8]

In [50]:
b[b%2 == 0]

array([4, 6, 8])

In [51]:
# Exercise 9 - print out the shape of the array b. (Shape is rows, columns)
b.shape

(2, 3)

In [52]:
# Exercise 10 - transpose the array b.
b.transpose()

array([[3, 6],
       [4, 7],
       [5, 8]])

In [55]:
# another method to transpose
b.T

array([[3, 6],
       [4, 7],
       [5, 8]])

In [53]:
# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)
b.flatten()

array([3, 4, 5, 6, 7, 8])

In [54]:
# Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)
b.reshape(6,1)

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

### Setup 3

In [101]:
# HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.

c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

In [102]:
c = np.array(c)

In [86]:
# Exercise 1 - Find the min, max, sum, and product of c.
c.min(), c.max(), c.sum(), c.prod()

(1, 9, 45, 362880)

In [87]:
# Exercise 2 - Determine the standard deviation of c.
c.std()

2.581988897471611

In [88]:
# Exercise 3 - Determine the variance of c.
c.var()

6.666666666666667

In [89]:
# Exercise 4 - Print out the shape of the array c
c.shape

(3, 3)

In [90]:
# Exercise 5 - Transpose c and print out transposed result.
c.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [114]:
# Exercise 6 - Get the dot product of the array c with c. 
np.dot(c,c)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [104]:
c.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [109]:
# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261
(c.transpose() * c).sum()

261

In [113]:
# Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.
(c * c.T).prod()

131681894400

### Setup 4

In [82]:
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]
d = np.array(d)
d

array([[ 90,  30,  45,   0, 120, 180],
       [ 45, -90, -30, 270,  90,   0],
       [ 60,  45, -45,  90, -45, 180]])

In [122]:
# Exercise 1 - Find the sine of all the numbers in d
np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

In [123]:
# Exercise 2 - Find the cosine of all the numbers in d
np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

In [124]:
# Exercise 3 - Find the tangent of all the numbers in d
np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

In [83]:
d<0

array([[False, False, False, False, False, False],
       [False,  True,  True, False, False, False],
       [False, False,  True, False,  True, False]])

In [125]:
# Exercise 4 - Find all the negative numbers in d
d[d<0]

array([-90, -30, -45, -45])

In [126]:
# Exercise 5 - Find all the positive numbers in d
d[d>0]

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

In [130]:
# Exercise 6 - Return an array of only the unique numbers in d.
np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

In [131]:
# Exercise 7 - Determine how many unique numbers there are in d.
len(np.unique(d))

11

In [132]:
# Exercise 8 - Print out the shape of d.
d.shape

(3, 6)

In [133]:
# Exercise 9 - Transpose and then print out the shape of d.
d.transpose()

array([[ 90,  45,  60],
       [ 30, -90,  45],
       [ 45, -30, -45],
       [  0, 270,  90],
       [120,  90, -45],
       [180,   0, 180]])

In [134]:
# Exercise 10 - Reshape d into an array of 9 x 2
d.reshape(9,2)

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])